/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0-beta.9.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface InsuranceForm {
  'id' : string,
  'status' : { 'completed' : null } |
    { 'draft' : null },
  'vozidlo' : Vehicle,
  'submitterName' : string,
  'paymentFrequency' : PaymentFrequency,
  'mileage' : [] | [string],
  'vlastnik' : [] | [Person],
  'createdAt' : Time,
  'hasTechnicalCertificate' : boolean,
  'isSameAsPojistnik' : boolean,
  'updatedAt' : Time,
  'hasImportedVehicle' : boolean,
  'sameOperator' : boolean,
  'insuranceOptions' : InsuranceOptions,
  'notes' : string,
  'viewedByAdmin' : boolean,
  'submitterEmail' : string,
  'pojistnik' : Person,
  'isPhysicalPerson' : boolean,
  'isSameAsProvozovatel' : boolean,
  'provozovatel' : Person,
}
export interface InsuranceOptions {
  'pojisteniNahradnihoVozidla' : boolean,
  'pojisteniGAP' : boolean,
  'povinneRuceni' : boolean,
  'pojisteniPrirodnichRizik' : boolean,
  'urazovePripojisteni' : boolean,
  'havarijniPojisteni' : boolean,
  'pojisteniSkel' : boolean,
  'pojisteniAsistence' : boolean,
}
export type PaymentFrequency = { 'pololetni' : null } |
  { 'ctvrtletni' : null } |
  { 'rocni' : null };
export interface Person {
  'ico' : string,
  'companyFieldsOnlyMode' : boolean,
  'name' : string,
  'isVatPayer' : boolean,
  'companyLastName' : string,
  'email' : string,
  'executiveName' : string,
  'isCompany' : boolean,
  'rodneCislo' : string,
  'address' : string,
  'phone' : string,
  'companyFirstName' : string,
  'executiveRodneCislo' : string,
}
export type Time = bigint;
export type UsageType = { 'autopujcovna' : null } |
  { 'sPravemPrednostniJizdy' : null } |
  { 'taxi' : null } |
  { 'autoskoly' : null } |
  { 'historickaVozidlaSeZvlastnimSPZ' : null } |
  { 'beznyProvoz' : null };
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface Vehicle {
  'spz' : string,
  'vin' : string,
  'weight' : [] | [bigint],
  'model' : string,
  'vehicleType' : Array<VehicleType>,
  'approximateValue' : [] | [bigint],
  'hasTechnicalCertificate' : boolean,
  'importedFromAbroad' : boolean,
  'usageType' : UsageType,
  'maxPower' : [] | [bigint],
  'engineCapacity' : [] | [bigint],
  'fuelType' : [] | [string],
  'brand' : string,
}
export type VehicleType = { 'obytny' : null } |
  { 'nakladni' : null } |
  { 'osobni' : null } |
  { 'motocykl' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createForm' : ActorMethod<[InsuranceForm], undefined>,
  'deleteForm' : ActorMethod<[string], undefined>,
  'getAllFormsSorted' : ActorMethod<[], Array<InsuranceForm>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getForm' : ActorMethod<[string], [] | [InsuranceForm]>,
  'getFormsByStatus' : ActorMethod<
    [{ 'completed' : null } | { 'draft' : null }],
    Array<InsuranceForm>
  >,
  'getNewFormsCount' : ActorMethod<[], bigint>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'initializeAccessControl' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'markAllFormsAsViewed' : ActorMethod<[], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateForm' : ActorMethod<[InsuranceForm], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];