/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0-beta.9.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const VehicleType = IDL.Variant({
  'obytny' : IDL.Null,
  'nakladni' : IDL.Null,
  'osobni' : IDL.Null,
  'motocykl' : IDL.Null,
});
export const UsageType = IDL.Variant({
  'autopujcovna' : IDL.Null,
  'sPravemPrednostniJizdy' : IDL.Null,
  'taxi' : IDL.Null,
  'autoskoly' : IDL.Null,
  'historickaVozidlaSeZvlastnimSPZ' : IDL.Null,
  'beznyProvoz' : IDL.Null,
});
export const Vehicle = IDL.Record({
  'spz' : IDL.Text,
  'vin' : IDL.Text,
  'weight' : IDL.Opt(IDL.Nat),
  'model' : IDL.Text,
  'vehicleType' : IDL.Vec(VehicleType),
  'approximateValue' : IDL.Opt(IDL.Nat),
  'hasTechnicalCertificate' : IDL.Bool,
  'importedFromAbroad' : IDL.Bool,
  'usageType' : UsageType,
  'maxPower' : IDL.Opt(IDL.Nat),
  'engineCapacity' : IDL.Opt(IDL.Nat),
  'fuelType' : IDL.Opt(IDL.Text),
  'brand' : IDL.Text,
});
export const PaymentFrequency = IDL.Variant({
  'pololetni' : IDL.Null,
  'ctvrtletni' : IDL.Null,
  'rocni' : IDL.Null,
});
export const Person = IDL.Record({
  'ico' : IDL.Text,
  'companyFieldsOnlyMode' : IDL.Bool,
  'name' : IDL.Text,
  'isVatPayer' : IDL.Bool,
  'companyLastName' : IDL.Text,
  'email' : IDL.Text,
  'executiveName' : IDL.Text,
  'isCompany' : IDL.Bool,
  'rodneCislo' : IDL.Text,
  'address' : IDL.Text,
  'phone' : IDL.Text,
  'companyFirstName' : IDL.Text,
  'executiveRodneCislo' : IDL.Text,
});
export const Time = IDL.Int;
export const InsuranceOptions = IDL.Record({
  'pojisteniNahradnihoVozidla' : IDL.Bool,
  'pojisteniGAP' : IDL.Bool,
  'povinneRuceni' : IDL.Bool,
  'pojisteniPrirodnichRizik' : IDL.Bool,
  'urazovePripojisteni' : IDL.Bool,
  'havarijniPojisteni' : IDL.Bool,
  'pojisteniSkel' : IDL.Bool,
  'pojisteniAsistence' : IDL.Bool,
});
export const InsuranceForm = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Variant({ 'completed' : IDL.Null, 'draft' : IDL.Null }),
  'vozidlo' : Vehicle,
  'submitterName' : IDL.Text,
  'paymentFrequency' : PaymentFrequency,
  'mileage' : IDL.Opt(IDL.Text),
  'vlastnik' : IDL.Opt(Person),
  'createdAt' : Time,
  'hasTechnicalCertificate' : IDL.Bool,
  'isSameAsPojistnik' : IDL.Bool,
  'updatedAt' : Time,
  'hasImportedVehicle' : IDL.Bool,
  'sameOperator' : IDL.Bool,
  'insuranceOptions' : InsuranceOptions,
  'notes' : IDL.Text,
  'viewedByAdmin' : IDL.Bool,
  'submitterEmail' : IDL.Text,
  'pojistnik' : Person,
  'isPhysicalPerson' : IDL.Bool,
  'isSameAsProvozovatel' : IDL.Bool,
  'provozovatel' : Person,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createForm' : IDL.Func([InsuranceForm], [], []),
  'deleteForm' : IDL.Func([IDL.Text], [], []),
  'getAllFormsSorted' : IDL.Func([], [IDL.Vec(InsuranceForm)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getForm' : IDL.Func([IDL.Text], [IDL.Opt(InsuranceForm)], ['query']),
  'getFormsByStatus' : IDL.Func(
      [IDL.Variant({ 'completed' : IDL.Null, 'draft' : IDL.Null })],
      [IDL.Vec(InsuranceForm)],
      ['query'],
    ),
  'getNewFormsCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'initializeAccessControl' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'markAllFormsAsViewed' : IDL.Func([], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateForm' : IDL.Func([InsuranceForm], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const VehicleType = IDL.Variant({
    'obytny' : IDL.Null,
    'nakladni' : IDL.Null,
    'osobni' : IDL.Null,
    'motocykl' : IDL.Null,
  });
  const UsageType = IDL.Variant({
    'autopujcovna' : IDL.Null,
    'sPravemPrednostniJizdy' : IDL.Null,
    'taxi' : IDL.Null,
    'autoskoly' : IDL.Null,
    'historickaVozidlaSeZvlastnimSPZ' : IDL.Null,
    'beznyProvoz' : IDL.Null,
  });
  const Vehicle = IDL.Record({
    'spz' : IDL.Text,
    'vin' : IDL.Text,
    'weight' : IDL.Opt(IDL.Nat),
    'model' : IDL.Text,
    'vehicleType' : IDL.Vec(VehicleType),
    'approximateValue' : IDL.Opt(IDL.Nat),
    'hasTechnicalCertificate' : IDL.Bool,
    'importedFromAbroad' : IDL.Bool,
    'usageType' : UsageType,
    'maxPower' : IDL.Opt(IDL.Nat),
    'engineCapacity' : IDL.Opt(IDL.Nat),
    'fuelType' : IDL.Opt(IDL.Text),
    'brand' : IDL.Text,
  });
  const PaymentFrequency = IDL.Variant({
    'pololetni' : IDL.Null,
    'ctvrtletni' : IDL.Null,
    'rocni' : IDL.Null,
  });
  const Person = IDL.Record({
    'ico' : IDL.Text,
    'companyFieldsOnlyMode' : IDL.Bool,
    'name' : IDL.Text,
    'isVatPayer' : IDL.Bool,
    'companyLastName' : IDL.Text,
    'email' : IDL.Text,
    'executiveName' : IDL.Text,
    'isCompany' : IDL.Bool,
    'rodneCislo' : IDL.Text,
    'address' : IDL.Text,
    'phone' : IDL.Text,
    'companyFirstName' : IDL.Text,
    'executiveRodneCislo' : IDL.Text,
  });
  const Time = IDL.Int;
  const InsuranceOptions = IDL.Record({
    'pojisteniNahradnihoVozidla' : IDL.Bool,
    'pojisteniGAP' : IDL.Bool,
    'povinneRuceni' : IDL.Bool,
    'pojisteniPrirodnichRizik' : IDL.Bool,
    'urazovePripojisteni' : IDL.Bool,
    'havarijniPojisteni' : IDL.Bool,
    'pojisteniSkel' : IDL.Bool,
    'pojisteniAsistence' : IDL.Bool,
  });
  const InsuranceForm = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Variant({ 'completed' : IDL.Null, 'draft' : IDL.Null }),
    'vozidlo' : Vehicle,
    'submitterName' : IDL.Text,
    'paymentFrequency' : PaymentFrequency,
    'mileage' : IDL.Opt(IDL.Text),
    'vlastnik' : IDL.Opt(Person),
    'createdAt' : Time,
    'hasTechnicalCertificate' : IDL.Bool,
    'isSameAsPojistnik' : IDL.Bool,
    'updatedAt' : Time,
    'hasImportedVehicle' : IDL.Bool,
    'sameOperator' : IDL.Bool,
    'insuranceOptions' : InsuranceOptions,
    'notes' : IDL.Text,
    'viewedByAdmin' : IDL.Bool,
    'submitterEmail' : IDL.Text,
    'pojistnik' : Person,
    'isPhysicalPerson' : IDL.Bool,
    'isSameAsProvozovatel' : IDL.Bool,
    'provozovatel' : Person,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createForm' : IDL.Func([InsuranceForm], [], []),
    'deleteForm' : IDL.Func([IDL.Text], [], []),
    'getAllFormsSorted' : IDL.Func([], [IDL.Vec(InsuranceForm)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getForm' : IDL.Func([IDL.Text], [IDL.Opt(InsuranceForm)], ['query']),
    'getFormsByStatus' : IDL.Func(
        [IDL.Variant({ 'completed' : IDL.Null, 'draft' : IDL.Null })],
        [IDL.Vec(InsuranceForm)],
        ['query'],
      ),
    'getNewFormsCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'initializeAccessControl' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'markAllFormsAsViewed' : IDL.Func([], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateForm' : IDL.Func([InsuranceForm], [], []),
  });
};

export const init = ({ IDL }) => { return []; };