/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0-beta.9.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Person {
    ico: string;
    companyFieldsOnlyMode: boolean;
    name: string;
    isVatPayer: boolean;
    companyLastName: string;
    email: string;
    executiveName: string;
    isCompany: boolean;
    rodneCislo: string;
    address: string;
    phone: string;
    companyFirstName: string;
    executiveRodneCislo: string;
}
export type Time = bigint;
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface InsuranceForm {
    id: string;
    status: Variant_completed_draft;
    vozidlo: Vehicle;
    submitterName: string;
    paymentFrequency: PaymentFrequency;
    mileage?: string;
    vlastnik?: Person;
    createdAt: Time;
    hasTechnicalCertificate: boolean;
    isSameAsPojistnik: boolean;
    updatedAt: Time;
    hasImportedVehicle: boolean;
    sameOperator: boolean;
    insuranceOptions: InsuranceOptions;
    notes: string;
    viewedByAdmin: boolean;
    submitterEmail: string;
    pojistnik: Person;
    isPhysicalPerson: boolean;
    isSameAsProvozovatel: boolean;
    provozovatel: Person;
}
export interface InsuranceOptions {
    pojisteniNahradnihoVozidla: boolean;
    pojisteniGAP: boolean;
    povinneRuceni: boolean;
    pojisteniPrirodnichRizik: boolean;
    urazovePripojisteni: boolean;
    havarijniPojisteni: boolean;
    pojisteniSkel: boolean;
    pojisteniAsistence: boolean;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface Vehicle {
    spz: string;
    vin: string;
    weight?: bigint;
    model: string;
    vehicleType: Array<VehicleType>;
    approximateValue?: bigint;
    hasTechnicalCertificate: boolean;
    importedFromAbroad: boolean;
    usageType: UsageType;
    maxPower?: bigint;
    engineCapacity?: bigint;
    fuelType?: string;
    brand: string;
}
export interface UserProfile {
    name: string;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export enum PaymentFrequency {
    pololetni = "pololetni",
    ctvrtletni = "ctvrtletni",
    rocni = "rocni"
}
export enum UsageType {
    autopujcovna = "autopujcovna",
    sPravemPrednostniJizdy = "sPravemPrednostniJizdy",
    taxi = "taxi",
    autoskoly = "autoskoly",
    historickaVozidlaSeZvlastnimSPZ = "historickaVozidlaSeZvlastnimSPZ",
    beznyProvoz = "beznyProvoz"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum Variant_completed_draft {
    completed = "completed",
    draft = "draft"
}
export enum VehicleType {
    obytny = "obytny",
    nakladni = "nakladni",
    osobni = "osobni",
    motocykl = "motocykl"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createForm(form: InsuranceForm): Promise<void>;
    deleteForm(id: string): Promise<void>;
    getAllFormsSorted(): Promise<Array<InsuranceForm>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getForm(id: string): Promise<InsuranceForm | null>;
    getFormsByStatus(status: Variant_completed_draft): Promise<Array<InsuranceForm>>;
    getNewFormsCount(): Promise<bigint>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    initializeAccessControl(): Promise<void>;
    isCallerAdmin(): Promise<boolean>;
    markAllFormsAsViewed(): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    updateForm(form: InsuranceForm): Promise<void>;
}
import type { InsuranceForm as _InsuranceForm, InsuranceOptions as _InsuranceOptions, PaymentFrequency as _PaymentFrequency, Person as _Person, Time as _Time, UsageType as _UsageType, UserProfile as _UserProfile, UserRole as _UserRole, Vehicle as _Vehicle, VehicleType as _VehicleType, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this.uploadFile, this.downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this.uploadFile, this.downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this.uploadFile, this.downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this.uploadFile, this.downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this.uploadFile, this.downloadFile, arg1));
            return result;
        }
    }
    async createForm(arg0: InsuranceForm): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createForm(to_candid_InsuranceForm_n10(this.uploadFile, this.downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createForm(to_candid_InsuranceForm_n10(this.uploadFile, this.downloadFile, arg0));
            return result;
        }
    }
    async deleteForm(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteForm(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteForm(arg0);
            return result;
        }
    }
    async getAllFormsSorted(): Promise<Array<InsuranceForm>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllFormsSorted();
                return from_candid_vec_n22(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllFormsSorted();
            return from_candid_vec_n22(this.uploadFile, this.downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n37(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n37(this.uploadFile, this.downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n38(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n38(this.uploadFile, this.downloadFile, result);
        }
    }
    async getForm(arg0: string): Promise<InsuranceForm | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getForm(arg0);
                return from_candid_opt_n40(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getForm(arg0);
            return from_candid_opt_n40(this.uploadFile, this.downloadFile, result);
        }
    }
    async getFormsByStatus(arg0: Variant_completed_draft): Promise<Array<InsuranceForm>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFormsByStatus(to_candid_variant_n12(this.uploadFile, this.downloadFile, arg0));
                return from_candid_vec_n22(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFormsByStatus(to_candid_variant_n12(this.uploadFile, this.downloadFile, arg0));
            return from_candid_vec_n22(this.uploadFile, this.downloadFile, result);
        }
    }
    async getNewFormsCount(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getNewFormsCount();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNewFormsCount();
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n37(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n37(this.uploadFile, this.downloadFile, result);
        }
    }
    async initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initializeAccessControl();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async markAllFormsAsViewed(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markAllFormsAsViewed();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markAllFormsAsViewed();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async updateForm(arg0: InsuranceForm): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateForm(to_candid_InsuranceForm_n10(this.uploadFile, this.downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateForm(to_candid_InsuranceForm_n10(this.uploadFile, this.downloadFile, arg0));
            return result;
        }
    }
}
function from_candid_InsuranceForm_n23(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _InsuranceForm): InsuranceForm {
    return from_candid_record_n24(uploadFile, downloadFile, value);
}
function from_candid_PaymentFrequency_n34(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaymentFrequency): PaymentFrequency {
    return from_candid_variant_n35(uploadFile, downloadFile, value);
}
function from_candid_UsageType_n31(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UsageType): UsageType {
    return from_candid_variant_n32(uploadFile, downloadFile, value);
}
function from_candid_UserRole_n38(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n39(uploadFile, downloadFile, value);
}
function from_candid_VehicleType_n29(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _VehicleType): VehicleType {
    return from_candid_variant_n30(uploadFile, downloadFile, value);
}
function from_candid_Vehicle_n26(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Vehicle): Vehicle {
    return from_candid_record_n27(uploadFile, downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(uploadFile, downloadFile, value);
}
function from_candid_opt_n33(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n36(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Person]): Person | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n37(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n40(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_InsuranceForm]): InsuranceForm | null {
    return value.length === 0 ? null : from_candid_InsuranceForm_n23(uploadFile, downloadFile, value[0]);
}
function from_candid_opt_n6(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n24(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: {
        completed: null;
    } | {
        draft: null;
    };
    vozidlo: _Vehicle;
    submitterName: string;
    paymentFrequency: _PaymentFrequency;
    mileage: [] | [string];
    vlastnik: [] | [_Person];
    createdAt: _Time;
    hasTechnicalCertificate: boolean;
    isSameAsPojistnik: boolean;
    updatedAt: _Time;
    hasImportedVehicle: boolean;
    sameOperator: boolean;
    insuranceOptions: _InsuranceOptions;
    notes: string;
    viewedByAdmin: boolean;
    submitterEmail: string;
    pojistnik: _Person;
    isPhysicalPerson: boolean;
    isSameAsProvozovatel: boolean;
    provozovatel: _Person;
}): {
    id: string;
    status: Variant_completed_draft;
    vozidlo: Vehicle;
    submitterName: string;
    paymentFrequency: PaymentFrequency;
    mileage?: string;
    vlastnik?: Person;
    createdAt: Time;
    hasTechnicalCertificate: boolean;
    isSameAsPojistnik: boolean;
    updatedAt: Time;
    hasImportedVehicle: boolean;
    sameOperator: boolean;
    insuranceOptions: InsuranceOptions;
    notes: string;
    viewedByAdmin: boolean;
    submitterEmail: string;
    pojistnik: Person;
    isPhysicalPerson: boolean;
    isSameAsProvozovatel: boolean;
    provozovatel: Person;
} {
    return {
        id: value.id,
        status: from_candid_variant_n25(uploadFile, downloadFile, value.status),
        vozidlo: from_candid_Vehicle_n26(uploadFile, downloadFile, value.vozidlo),
        submitterName: value.submitterName,
        paymentFrequency: from_candid_PaymentFrequency_n34(uploadFile, downloadFile, value.paymentFrequency),
        mileage: record_opt_to_undefined(from_candid_opt_n33(uploadFile, downloadFile, value.mileage)),
        vlastnik: record_opt_to_undefined(from_candid_opt_n36(uploadFile, downloadFile, value.vlastnik)),
        createdAt: value.createdAt,
        hasTechnicalCertificate: value.hasTechnicalCertificate,
        isSameAsPojistnik: value.isSameAsPojistnik,
        updatedAt: value.updatedAt,
        hasImportedVehicle: value.hasImportedVehicle,
        sameOperator: value.sameOperator,
        insuranceOptions: value.insuranceOptions,
        notes: value.notes,
        viewedByAdmin: value.viewedByAdmin,
        submitterEmail: value.submitterEmail,
        pojistnik: value.pojistnik,
        isPhysicalPerson: value.isPhysicalPerson,
        isSameAsProvozovatel: value.isSameAsProvozovatel,
        provozovatel: value.provozovatel
    };
}
function from_candid_record_n27(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    spz: string;
    vin: string;
    weight: [] | [bigint];
    model: string;
    vehicleType: Array<_VehicleType>;
    approximateValue: [] | [bigint];
    hasTechnicalCertificate: boolean;
    importedFromAbroad: boolean;
    usageType: _UsageType;
    maxPower: [] | [bigint];
    engineCapacity: [] | [bigint];
    fuelType: [] | [string];
    brand: string;
}): {
    spz: string;
    vin: string;
    weight?: bigint;
    model: string;
    vehicleType: Array<VehicleType>;
    approximateValue?: bigint;
    hasTechnicalCertificate: boolean;
    importedFromAbroad: boolean;
    usageType: UsageType;
    maxPower?: bigint;
    engineCapacity?: bigint;
    fuelType?: string;
    brand: string;
} {
    return {
        spz: value.spz,
        vin: value.vin,
        weight: record_opt_to_undefined(from_candid_opt_n7(uploadFile, downloadFile, value.weight)),
        model: value.model,
        vehicleType: from_candid_vec_n28(uploadFile, downloadFile, value.vehicleType),
        approximateValue: record_opt_to_undefined(from_candid_opt_n7(uploadFile, downloadFile, value.approximateValue)),
        hasTechnicalCertificate: value.hasTechnicalCertificate,
        importedFromAbroad: value.importedFromAbroad,
        usageType: from_candid_UsageType_n31(uploadFile, downloadFile, value.usageType),
        maxPower: record_opt_to_undefined(from_candid_opt_n7(uploadFile, downloadFile, value.maxPower)),
        engineCapacity: record_opt_to_undefined(from_candid_opt_n7(uploadFile, downloadFile, value.engineCapacity)),
        fuelType: record_opt_to_undefined(from_candid_opt_n33(uploadFile, downloadFile, value.fuelType)),
        brand: value.brand
    };
}
function from_candid_record_n5(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(uploadFile, downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(uploadFile, downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n25(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    completed: null;
} | {
    draft: null;
}): Variant_completed_draft {
    return "completed" in value ? Variant_completed_draft.completed : "draft" in value ? Variant_completed_draft.draft : value;
}
function from_candid_variant_n30(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    obytny: null;
} | {
    nakladni: null;
} | {
    osobni: null;
} | {
    motocykl: null;
}): VehicleType {
    return "obytny" in value ? VehicleType.obytny : "nakladni" in value ? VehicleType.nakladni : "osobni" in value ? VehicleType.osobni : "motocykl" in value ? VehicleType.motocykl : value;
}
function from_candid_variant_n32(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    autopujcovna: null;
} | {
    sPravemPrednostniJizdy: null;
} | {
    taxi: null;
} | {
    autoskoly: null;
} | {
    historickaVozidlaSeZvlastnimSPZ: null;
} | {
    beznyProvoz: null;
}): UsageType {
    return "autopujcovna" in value ? UsageType.autopujcovna : "sPravemPrednostniJizdy" in value ? UsageType.sPravemPrednostniJizdy : "taxi" in value ? UsageType.taxi : "autoskoly" in value ? UsageType.autoskoly : "historickaVozidlaSeZvlastnimSPZ" in value ? UsageType.historickaVozidlaSeZvlastnimSPZ : "beznyProvoz" in value ? UsageType.beznyProvoz : value;
}
function from_candid_variant_n35(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pololetni: null;
} | {
    ctvrtletni: null;
} | {
    rocni: null;
}): PaymentFrequency {
    return "pololetni" in value ? PaymentFrequency.pololetni : "ctvrtletni" in value ? PaymentFrequency.ctvrtletni : "rocni" in value ? PaymentFrequency.rocni : value;
}
function from_candid_variant_n39(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n22(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_InsuranceForm>): Array<InsuranceForm> {
    return value.map((x)=>from_candid_InsuranceForm_n23(uploadFile, downloadFile, x));
}
function from_candid_vec_n28(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_VehicleType>): Array<VehicleType> {
    return value.map((x)=>from_candid_VehicleType_n29(uploadFile, downloadFile, x));
}
function to_candid_InsuranceForm_n10(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: InsuranceForm): _InsuranceForm {
    return to_candid_record_n11(uploadFile, downloadFile, value);
}
function to_candid_PaymentFrequency_n20(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentFrequency): _PaymentFrequency {
    return to_candid_variant_n21(uploadFile, downloadFile, value);
}
function to_candid_UsageType_n18(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UsageType): _UsageType {
    return to_candid_variant_n19(uploadFile, downloadFile, value);
}
function to_candid_UserRole_n8(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n9(uploadFile, downloadFile, value);
}
function to_candid_VehicleType_n16(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: VehicleType): _VehicleType {
    return to_candid_variant_n17(uploadFile, downloadFile, value);
}
function to_candid_Vehicle_n13(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Vehicle): _Vehicle {
    return to_candid_record_n14(uploadFile, downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(uploadFile, downloadFile, value);
}
function to_candid_opt_n1(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(uploadFile, downloadFile, value));
}
function to_candid_record_n11(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: Variant_completed_draft;
    vozidlo: Vehicle;
    submitterName: string;
    paymentFrequency: PaymentFrequency;
    mileage?: string;
    vlastnik?: Person;
    createdAt: Time;
    hasTechnicalCertificate: boolean;
    isSameAsPojistnik: boolean;
    updatedAt: Time;
    hasImportedVehicle: boolean;
    sameOperator: boolean;
    insuranceOptions: InsuranceOptions;
    notes: string;
    viewedByAdmin: boolean;
    submitterEmail: string;
    pojistnik: Person;
    isPhysicalPerson: boolean;
    isSameAsProvozovatel: boolean;
    provozovatel: Person;
}): {
    id: string;
    status: {
        completed: null;
    } | {
        draft: null;
    };
    vozidlo: _Vehicle;
    submitterName: string;
    paymentFrequency: _PaymentFrequency;
    mileage: [] | [string];
    vlastnik: [] | [_Person];
    createdAt: _Time;
    hasTechnicalCertificate: boolean;
    isSameAsPojistnik: boolean;
    updatedAt: _Time;
    hasImportedVehicle: boolean;
    sameOperator: boolean;
    insuranceOptions: _InsuranceOptions;
    notes: string;
    viewedByAdmin: boolean;
    submitterEmail: string;
    pojistnik: _Person;
    isPhysicalPerson: boolean;
    isSameAsProvozovatel: boolean;
    provozovatel: _Person;
} {
    return {
        id: value.id,
        status: to_candid_variant_n12(uploadFile, downloadFile, value.status),
        vozidlo: to_candid_Vehicle_n13(uploadFile, downloadFile, value.vozidlo),
        submitterName: value.submitterName,
        paymentFrequency: to_candid_PaymentFrequency_n20(uploadFile, downloadFile, value.paymentFrequency),
        mileage: value.mileage ? candid_some(value.mileage) : candid_none(),
        vlastnik: value.vlastnik ? candid_some(value.vlastnik) : candid_none(),
        createdAt: value.createdAt,
        hasTechnicalCertificate: value.hasTechnicalCertificate,
        isSameAsPojistnik: value.isSameAsPojistnik,
        updatedAt: value.updatedAt,
        hasImportedVehicle: value.hasImportedVehicle,
        sameOperator: value.sameOperator,
        insuranceOptions: value.insuranceOptions,
        notes: value.notes,
        viewedByAdmin: value.viewedByAdmin,
        submitterEmail: value.submitterEmail,
        pojistnik: value.pojistnik,
        isPhysicalPerson: value.isPhysicalPerson,
        isSameAsProvozovatel: value.isSameAsProvozovatel,
        provozovatel: value.provozovatel
    };
}
function to_candid_record_n14(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    spz: string;
    vin: string;
    weight?: bigint;
    model: string;
    vehicleType: Array<VehicleType>;
    approximateValue?: bigint;
    hasTechnicalCertificate: boolean;
    importedFromAbroad: boolean;
    usageType: UsageType;
    maxPower?: bigint;
    engineCapacity?: bigint;
    fuelType?: string;
    brand: string;
}): {
    spz: string;
    vin: string;
    weight: [] | [bigint];
    model: string;
    vehicleType: Array<_VehicleType>;
    approximateValue: [] | [bigint];
    hasTechnicalCertificate: boolean;
    importedFromAbroad: boolean;
    usageType: _UsageType;
    maxPower: [] | [bigint];
    engineCapacity: [] | [bigint];
    fuelType: [] | [string];
    brand: string;
} {
    return {
        spz: value.spz,
        vin: value.vin,
        weight: value.weight ? candid_some(value.weight) : candid_none(),
        model: value.model,
        vehicleType: to_candid_vec_n15(uploadFile, downloadFile, value.vehicleType),
        approximateValue: value.approximateValue ? candid_some(value.approximateValue) : candid_none(),
        hasTechnicalCertificate: value.hasTechnicalCertificate,
        importedFromAbroad: value.importedFromAbroad,
        usageType: to_candid_UsageType_n18(uploadFile, downloadFile, value.usageType),
        maxPower: value.maxPower ? candid_some(value.maxPower) : candid_none(),
        engineCapacity: value.engineCapacity ? candid_some(value.engineCapacity) : candid_none(),
        fuelType: value.fuelType ? candid_some(value.fuelType) : candid_none(),
        brand: value.brand
    };
}
function to_candid_record_n3(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_variant_n12(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_completed_draft): {
    completed: null;
} | {
    draft: null;
} {
    return value == Variant_completed_draft.completed ? {
        completed: null
    } : value == Variant_completed_draft.draft ? {
        draft: null
    } : value;
}
function to_candid_variant_n17(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: VehicleType): {
    obytny: null;
} | {
    nakladni: null;
} | {
    osobni: null;
} | {
    motocykl: null;
} {
    return value == VehicleType.obytny ? {
        obytny: null
    } : value == VehicleType.nakladni ? {
        nakladni: null
    } : value == VehicleType.osobni ? {
        osobni: null
    } : value == VehicleType.motocykl ? {
        motocykl: null
    } : value;
}
function to_candid_variant_n19(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UsageType): {
    autopujcovna: null;
} | {
    sPravemPrednostniJizdy: null;
} | {
    taxi: null;
} | {
    autoskoly: null;
} | {
    historickaVozidlaSeZvlastnimSPZ: null;
} | {
    beznyProvoz: null;
} {
    return value == UsageType.autopujcovna ? {
        autopujcovna: null
    } : value == UsageType.sPravemPrednostniJizdy ? {
        sPravemPrednostniJizdy: null
    } : value == UsageType.taxi ? {
        taxi: null
    } : value == UsageType.autoskoly ? {
        autoskoly: null
    } : value == UsageType.historickaVozidlaSeZvlastnimSPZ ? {
        historickaVozidlaSeZvlastnimSPZ: null
    } : value == UsageType.beznyProvoz ? {
        beznyProvoz: null
    } : value;
}
function to_candid_variant_n21(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentFrequency): {
    pololetni: null;
} | {
    ctvrtletni: null;
} | {
    rocni: null;
} {
    return value == PaymentFrequency.pololetni ? {
        pololetni: null
    } : value == PaymentFrequency.ctvrtletni ? {
        ctvrtletni: null
    } : value == PaymentFrequency.rocni ? {
        rocni: null
    } : value;
}
function to_candid_variant_n9(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_vec_n15(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<VehicleType>): Array<_VehicleType> {
    return value.map((x)=>to_candid_VehicleType_n16(uploadFile, downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, uploadFile, downloadFile, options.processError);
}
